#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git',
  git: 'https://github.com/fnichol/chef-git.git'
cookbook 'build-essential'
cookbook 'openvpn'
cookbook 'htop'
cookbook 'python'
cookbook 'chef-server', 
  git: 'https://github.com/opscode-cookbooks/chef-server.git'
cookbook 'squid'
cookbook 'disco',
  git: 'git://github.com/eyecat/cookbook-disco.git'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

